// Register
export const  REGISTER_REQUEST =  'REGISTER_REQUEST'
export const  REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const  REGISTER_FAILURE = 'REGISTER_FAILURE'
// Login 
export const  LOGIN_REQUEST = 'LOGIN_REQUEST'
export const  LOGIN_SUCCESS = 'LOGIN_SUCCESS,'
export const  LOGIN_FAILURE = 'LOGIN_FAILURE'
// Fetch all blogs
export const FETCH_BLOG_REQUEST = 'FETCH_BLOG_REQUEST';
export const FETCH_BLOG_SUCCESS = 'FETCH_BLOG_SUCCESS';
export const FETCH_BLOG_FAILURE = 'FETCH_BLOG_FAILURE';

// Fetch single blog
export const FETCH_SINGLE_BLOG_REQUEST = 'FETCH_SINGLE_BLOG_REQUEST';
export const FETCH_SINGLE_BLOG_SUCCESS = 'FETCH_SINGLE_BLOG_SUCCESS';
export const FETCH_SINGLE_BLOG_FAILURE = 'FETCH_SINGLE_BLOG_FAILURE';

// Create blog
export const CREATE_BLOG_REQUEST = 'CREATE_BLOG_REQUEST';
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_FAILURE = 'CREATE_BLOG_FAILURE';

// Update blog
export const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_FAILURE = 'UPDATE_BLOG_FAILURE';

// Delete blog
export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAILURE = 'DELETE_BLOG_FAILURE';

// Add comment
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

// Fetch comment
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

// Like Comment
export const LIKE_BLOG_REQUEST = 'LIKE_BLOG_REQUEST';
export const LIKE_BLOG_SUCCESS = 'LIKE_BLOG_SUCCESS';
export const LIKE_BLOG_FAILURE = 'LIKE_BLOG_FAILURE';

// Delete Comment
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE'


// Logout

export const LOGOUT = 'LOGOUT'